### PR TITLE
Added Light/Dark mode support

### PR DESCRIPTION
**Pull request by codeDamon**
## Related Issue or bug
  Issue #10 - Light/Dark mode support added.

Filled the form: https://forms.gle/uTfMxj8282nzwPck8

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

Updated
screenshot_scan

### CODE REVIEW

**Comment by mishraaditya595** [comment]
Hey @codeDamon, I think you submitted a previous version of the apk. Can you resubmit it?

**Comment by codeDamon** [comment]
> Hey @codeDamon, I think you submitted a previous version of the apk. Can you resubmit it?

Oh! Re-submitted the form.

**Comment by mishraaditya595** [comment]
Hey @codeDamon, a few things that can be changed.
1. The filename colour does not look that great. 
2. You may change the icon of the file.
3. Try for a good looking actionbar. Like adding the appname or maybe an icon. 
4. Search bar does not look in sync in the light mode. Try to integrate the searchbar into the actionbar.

**Comment by codeDamon** [comment]
Talking about my PR, I targeted for implementing light/dark mode throughout the app.
If this functionality is okay, merge my PR #35 and then PR #37.

Now taking about other things (as you mentioned) will do them later.

**Pull request merged**
