### PR TITLE
Migrate from ListView to RecyclerView

### PR DESCRIPTION
**Pull request by codeDamon**
Fixes: Issue #11 

* Now the pdf document list is displayed via RecyclerView.
* Previously there was ListView implementation for the same.

Filled the form: https://forms.gle/uTfMxj8282nzwPck8

[Note: Only parts of code needed to be changed for this issue were changed, rest left unchanged.]

### CODE REVIEW

**Comment by mishraaditya595** [comment]
Hey @codeDamon, I just ran the apk and realised that no files are getting displayed in the recycler view & I think the app theme has been messed up a bit. The bottom nav bar appears black in the light mode. 

Try enabling requestlegacystorage in android manifest.

**Comment by codeDamon** [comment]
As already said - I only focused on this issue - "Converting listview to recyclerview", nothing else. Leaving all code as it was before.
If the task of converting listview to recyclerview is achieved successfully, merge it. 
Talking about themes, bottom nav bar, and storage - Create new issues.

**Comment by mishraaditya595** [comment]
The theme is working alright till now. It's your apk where it is not functioning, the contents which were being displayed in the listview are not getting displayed in the recycler view. I cannot merge it.

**Comment by codeDamon** [comment]
> The theme is working alright till now. It's your apk where it is not functioning, the contents which were being displayed in the listview are not getting displayed in the recycler view. I cannot merge it.

Okay I understand, But just review the codes and see what lines are being changed. No unnecessary lines of code added. I think contents are not even displayed before. Try it out.

**Comment by codeDamon** [comment]
I tested the app by adding dummy, hard-coded PDF files list. Its working completely fine. It seems app is not being able to read and write storage.

**Comment by codeDamon** [comment]
Have you seen the code?

**Pull request merged**
