### PR TITLE
Added Settings Page

### PR DESCRIPTION
**Pull request by codeDamon**
Issue #12 Solved

Added Settings Page
With:
  * Dark-Light Switcher with functionality
  * Privacy Policy and Open Source Licences options.

Added colors-night.xml:
  * To change colors with theme

## Screenshots

Screenshot_demo
Updated

### CODE REVIEW

**Comment by mishraaditya595** [comment]
Please attach the apk file here.

**Comment by codeDamon** [comment]
We can only attach file less than 10MB here. APK file size is around 50MB.

**Comment by mishraaditya595** [comment]
https://forms.gle/uTfMxj8282nzwPck8
Try this link

**Comment by codeDamon** [comment]
> https://forms.gle/uTfMxj8282nzwPck8
> Try this link

Filled the form

**Comment by mishraaditya595** [comment]
Hey @codeDamon, I think there is an issue with the bottom nav view. The icons appear black on the greyish background which it should not. They were white.

**Comment by codeDamon** [comment]
> Hey @codeDamon, I think there is an issue with the bottom nav view. The icons appear black on the greyish background which it should not. They were white.

It happen when app is in Light mode. For Dark mode its fine. 
The reason for this:
* BottomNavigationView has background color as grey.
* Ideally when switching to Light mode, BottomNavigationView should have white background and black icons and in dark mode it should be grey with white icons.

I haven't disturbed any other part of the code, except needed for this issue. Moreover there are no color theming for any pages, like in fragment_home.xml its background is black. We have to change these colors to dynamic colors (based on current theme of the app)

**Comment by codeDamon** [comment]
If you want you can create an issue to Change colors of the complete app to fit light/dark mode. 
I can work on that issue.

**Comment by mishraaditya595** [comment]
> If you want you can create an issue to Change colors of the complete app to fit light/dark mode.
> I can work on that issue.

Sounds good to me. I will increase the level of the PR.

**Comment by codeDamon** [comment]
Please create another issue for that work.

**Comment by mishraaditya595** [comment]
> Please create another issue for that work. I will complete that within 1 day.

Check if the work falls under the embargo of issue #10.

**Comment by codeDamon** [comment]
Issue #10 is a broader issue compared to adding light/dark support theme throughout the app. If you want I can work on that as well. 
Please merge this pull request and then I start working on issue #10 . It hardly take a day to solve this.

**Comment by mishraaditya595** [comment]
I recommend you to start working on that. I will merge this PR in a day or two as currently, I am working on fixing some core bugs of the app. Will merge it once that is sorted.

**Comment by codeDamon** [comment]
Okay, I started :D

**Pull request merged**
