### PR TITLE
Update README.md

### LINKED ISSUE #8: Improvements to README.md
The readme section of the project is very basic. A lot of improvements can be done.

### PR DESCRIPTION
**Pull request by kanishkaa24**
Added contributors and logo.
Closes #8

### CODE REVIEW

**Comment by mishraaditya595** [comment]
Are the names of the contributors automatically added or have to be done manually every time?

**Comment by kanishkaa24** [comment]
You'll have to add them.

**Comment by mishraaditya595** [comment]
This will be a tedious task for project managers. And as the project grows, it might receive contributions from many and having all of them on the readme will look odd and unprofessional.

**Comment by kanishkaa24** [comment]
Then shall I remove the contributors?

**Comment by mishraaditya595** [comment]
Yes, and for the logo, replace with [this](https://github.com/mishraaditya595/ScanIt/blob/master/app/src/main/res/mipmap-xxxhdpi/scanit_icon_round.png) and align it to the middle.

**Comment by kanishkaa24** [comment]
Noted

**Comment by kanishkaa24** [comment]
Made suggested changes. @mishraaditya595 
Closes #8

**Pull request merged**
